### ISSUE TITLE
Make imports exclusion smarter

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#163]
Currently only directly imported packages are excluded from build. It would be great if transitive dependencies only used from imported packages would be excluded too.

This would ease project's configurations a lot.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
