### ISSUE TITLE
Proposal: support for dynamic import(…)

### ISSUE THREAD

**Issue by yuchi** [liferay/liferay-js-toolkit#17]
See WebPack feature here: https://webpack.js.org/api/module-methods/#import-

In short we should be able to support the following usage:

```js
import React from 'react';
import Loadable from 'react-loadable';

function Loading() {
  return <p>Loading…</p>;
}

const LoadableComponent = Loadable({
  loader: () => import('./my-split-component'),
  loading: Loading,
});

export default class App extends React.Component {
  render() {
    return <LoadableComponent/>;
  }
}
```

Please notice how `import( … )` returns a _Promise_ to the exported module (works with `module.exports` with `__esModule`).

More or less should equal to:

```js
function import(name) {
  return new Promise((resolve, reject) => require(name, resolve, reject));
}
```

**Comment by yuchi** [comment]
Actually could be a new locally available function. If this was the case then this issue should be moved to the Liferay AMD Loader repo.

**Comment by jbalsas** [comment]
Hey @yuchi, I haven't had time to look into it, but I think there are babel plugins to transform dynamic import to require, which then should be covered by our current loader feature set.

**Comment by yuchi** [comment]
Nice pointer, indeed there’s at least one: [thgreasi/babel-plugin-system-import-transformer](https://github.com/thgreasi/babel-plugin-system-import-transformer).

It should be modified to handle the namespaced Loader but looks promising.

**Comment by izaera** [comment]
The namespaced Loader can be handled by another plugin that can be chained after. Something similar to https://github.com/liferay/liferay-npm-build-tools/tree/master/packages/babel-plugin-namespace-amd-define but for `require()`

**Comment by izaera** [comment]
Closing this as it seems to have a workaround. Feel free to reopen it if you feel it is still necessary.
