### ISSUE TITLE
Research the use of standard npm mechanisms to handle package/module names and resolutions

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#171]
Instead of trying to mimick what node and npm do, use their code if possible to resolve module names, projects, and, in general, apply all the npm logic needed to bundle packages.

**Comment by rt-jar** [comment]
I tried several npm projects which were working with npm; but liferay bundler was failed to bundle same. It's much needed feature. So that everything available in npm could work as is in liferay as well.

**Comment by izaera** [comment]
I'm closing this since we seem to be using `require` and `require.resolve` in almost all places. We have even moved some projects to yarn and the bundler keeps working seamlessly.

In case some error of this kind appears in the future, we will tackle it in its own bug. There's no point in auditing the whole code base now to see if there's any place of improvement, given the reasons above.
