### ISSUE TITLE
Let bundler presets be extended

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#194]
Currently bundler presets are merged with the local `.npmbundlerrc` file found in the project, but there's no way for one preset to reference another preset. This is not an ideal situation, because it leads to copy-paste and code duplication when we want to extend another preset.

Thus, we need a way to compose presets with the help of a library like [merge](https://www.npmjs.com/package/merge), for instance.

However, we need to be careful when defining how the merge process takes place: 

1. What takes precedence over what
2. How deep does the merge takes place
3. Are we going to support deletions to already existing config values?
4. Are we going to support modifications to already existing config values?
5. In case 3 or 4 reply is yes, how?

**Comment by ambrinchaudhary** [comment]
This issue affects https://issues.liferay.com/browse/LPS-91049. 
In DM we are currently using the preset. But errors appear when we try to configure an import from `asset-taglib` because they are not properly loaded. 

This is what we have in `.npmbundlerrc`:
```
{
	"config": {
		"imports": {
			"asset-taglib": {
				"/": ">=4.0.0"
			},
			"frontend-js-web": {
				"/": ">=3.0.0"
			}
		}
	},
	"ignore": [
		"**/document_library/js/*.js"
	],
       "preset": "liferay-npm-bundler-preset-liferay-dev"
}
```

**Comment by jbalsas** [comment]
Although ideally we'd like to have a deep-merge smart feature, a fastest approach is to just add the proper configuration in the [preset](https://github.com/bryceosterhaus/liferay-npm-tools/tree/master/packages/liferay-npm-bundler-preset-liferay-dev).

@ambrinchaudhary, could you take https://github.com/bryceosterhaus/liferay-npm-tools/pull/13 as an example and add the necessary `imports`? This would also result in every other Portal module automatically importing the exported packages from `asset-taglib`.

**Comment by izaera** [comment]
I'm closing this as it is much easier to let users specify configuration in a `.js` file (as in [this commit](https://github.com/izaera/liferay-js-toolkit/commit/f29eef02c7b175436a5aa8e80a48f2cc82534980) ).

If we need to extend presets for bundler 2 in the future we may simply backport that feature.
