### ISSUE TITLE
Allow developer to specify port for webpack 

### ISSUE THREAD

**Issue by travisrcory** [liferay/liferay-js-toolkit#265]
https://github.com/liferay/liferay-npm-build-tools/blob/develop/packages/liferay-npm-build-support/src/resources/start/webpack.config.js.ejs

Add support for port specification in devServer options

**Comment by izaera** [comment]
This should not be closed as it is not yet merged in master.

**Comment by reinrl** [comment]
This change seems to have one big downside - if you don't specify a port in your .npmbuildrc, and if something is already running on port 8080 (such as another project using this same package), attempting to start your project results in a port conflict error. Is there a way to optionally support configuring a port, without forcing a default (allowing the next available to be grabbed)?
