### ISSUE TITLE
Custom configuration squashes preset configuration

### ISSUE THREAD

**Issue by jbalsas** [liferay/liferay-js-toolkit#294]
Currently, custom configuration and preset configuration are squashed using `Object.assign` which causes the unexpected behaviour of preset configuration not being augmented.

For example, given the following `.npmbundlerrc`:

```javascript
{
    config: { 
        imports: { 
            'asset-taglib': {...} 
        } 
    },
    preset: 'liferay-npm-bundler-preset-liferay-dev'
}
```

The resulting configuration applied won't contain all the `imports` configuration of the preset. 

To match user expectations (and fully leverage presets) we should probably need a `merge` strategy like the one implemented by `liferay-npm-scripts` to resolve configurations: https://github.com/liferay/liferay-npm-tools/blob/master/packages/liferay-npm-scripts/src/utils/get-merged-config.js#L25-L30

**Comment by izaera** [comment]
This is implemented in https://github.com/liferay/liferay-npm-build-tools/pull/295
