### ISSUE TITLE
Typo in React portlet Language.properties

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-js-toolkit#304]
The autogenerated `features/localization/Language.properties` file has 
```
porlet-namespace=Porlet Namespace
```
instead of 
```
portlet-namespace=Portlet Namespace
```

**Comment by izaera** [comment]
This is fixed in [this commit](https://github.com/liferay/liferay-npm-build-tools/commit/f3b437f51944df9507db68f8df0d3c67851526d5#diff-be39007dc4848e66c174fa91bde0faa3) for issue #260
