### ISSUE TITLE
Add support for specifying custom MANIFEST.MF properties

### ISSUE THREAD

**Issue by rozamirandar** [liferay/liferay-js-toolkit#335]
It would be nice to have an extension point to provide custom properties in the MANIFEST.MF file.

Example:

Bundle-SymbolicName: sample-senna-bundle
Bundle-Version: 1.0.0
**Custom-key-version**: 1.0.0-build-14

**Comment by izaera** [comment]
The configuration option will be named `create-jar.customManifestHeaders`.

Example:

```json
{
  "create-jar": {
    "customManifestHeaders": {
      "Project-Name": "A Project",
      "Responsible": "john.doe@somewhere.net"
    }
  }
}
```
