### ISSUE TITLE
How to use scss

### ISSUE THREAD

**Issue by phillipsheridan** [liferay/liferay-js-toolkit#352]
I was able to get sass working in the local webpack instance by changing my rules in .npmbuildrc to 

`"rules": [
			{
        "test": "\\.(sa|sc|c)ss$",
        "use": ["style-loader", "css-loader", "sass-loader"]
      },
			{
				"test": "src\\\\.*\\.js$",
				"use": "babel-loader"
			}
		]`

and importing the .scss file in my entry point.

but when I deploy to liferay, it adds the .js extension to the scss import so it can't be found.

Is there a better way to go about using sass?

**Comment by jbalsas** [comment]
Hey @phillipsheridan, as I stated, we're trying to cover this in general as part of [Add support to provide CSS code as AMD modules](https://github.com/liferay/liferay-js-toolkit/issues/303) which has been drafted at https://github.com/liferay/liferay-js-toolkit/pull/356.

Could you please take a look to see if that would cover your use case?

**Comment by phillipsheridan** [comment]
Looks like you guys are already taking care of it. Thanks.
