### ISSUE TITLE
How to use .env variables

### ISSUE THREAD

**Issue by phillipsheridan** [liferay/liferay-js-toolkit#353]
I need a way to be able to quickly switch between dev and prod mode. Normally in our hacky webpack approach we use the dotenv-webpack plugin.

**Comment by izaera** [comment]
Can you elaborate a bit? 

I've never used `.env` files but they just seem to be loaded by the `dotenv` package and put in `process.env` which is exactly the same thing that would happen if you set the environment variables manually, whether from the shell, in the npm script line, ....

So I would say you just need to tweak your build process to achieve whatever you want...

I'm closing this as answered. Feel free to reopen it if needed.
