### ISSUE TITLE
Can't see source maps inside liferay

### ISSUE THREAD

**Issue by phillipsheridan** [liferay/liferay-js-toolkit#354]
Is this normal or can we only see them when running locally in webpack?

**Comment by jbalsas** [comment]
Hey @phillipsheridan, I'm tentatively flagging this as a bug. 

You should definitely be able to see sourcemaps inside DXP. Could you please verify if your sourcemaps are being generated? If they are, are they being included in your resulting jar?

**Comment by phillipsheridan** [comment]
Looks like I spoke too soon on this one. I can see them, they are just not where I expected them. Sorry.

**Comment by jbalsas** [comment]
Thanks for answering back, @phillipsheridan!

Can you expand a little on what were your expectations and how they differ from what you found in reality? Maybe we can work towards aligning them in the future...

**Comment by phillipsheridan** [comment]
Hey, no problem.

Usually they are inside the webpack folder. But the application does not get bundled so it makes sense that they wouldn't be there.
