### ISSUE TITLE
How to configure specific javascript/react features in `npm run start`

### ISSUE THREAD

**Issue by phillipsheridan** [liferay/liferay-js-toolkit#355]
I managed to configure babel for the liferay build. But for the local lnbs build using 'npm start' for the webpack-server instance, I am not able to use any ECMA 2015 proposals like arrow function or any newer react features like <> ... </> as fragment, state outside of constructor, etc... I think I broke it because now it won't even recognize JSX.

**Comment by izaera** [comment]
The "start" feature is kind of experimental so unfortunately it just implements the bare minimum and it's internals are not fully documented yet.

However, in your project there must be a `.npmbuildrc` file, created by the Yeoman generator, which allows you to tune webpack's configuration for the `npm run start` target.

You can see an example of such file here -> https://github.com/izaera/liferay-js-toolkit-showcase/blob/react/packages/display-data-widget/.npmbuildrc

So, just add any plugin you may need there and it will be copied into the generated webpack configuration when `npm run start` is invoked.
