### ISSUE TITLE
Handling importing JSON-modules with require ('./data.json') 

### ISSUE THREAD

**Issue by j2k6** [liferay/liferay-js-toolkit#358]
Hello.
I stuck with bundling my application that require ajv module which has requires JSON-files in import section. 
How can I handle such situation? I did not find any hint in wiki yet.

**Comment by jbalsas** [comment]
Hey @j2k6, this is currently not possible directly. 

We're working to add loader support for the bundler so we can support cases like this as part of https://github.com/liferay/liferay-js-toolkit/issues/303.

**Comment by izaera** [comment]
Closing this as duplicate of #303
