### ISSUE TITLE
Don't Understand Trigger for AMD Module Loading

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#359]
When using the new npm bundler, what is the trigger that causes the various defines for modules inside my portlet JAR to run?

In other words, i am peering inside the generated JAR and see a manifest.json and a package.json, but no config.json which is what i would have expected to initiate the triggering of module loading (i.e. calls to Loader.define)

Can someone explain to me what the bundler injects that triggers the loading of AMD module definitions once the JAR is deployed?

Thanks

**Comment by mfreeman-xtivia** [comment]
Closing my own issue as this forum seems to be completely ignored by Liferay personnel

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, I want to think you're frustrated about something else, because I don't think this being opened less than 2 working days grants this kind of backlash.

We're also in the middle of summer vacation, which means half or our engineering staff is going in and out of PTO, so our response times might indeed be longer than usual.

This being said and until @izaera comes back, who can correct any mistakes I make, I think the answer you're looking for is two-fold:
- In [How to use liferay npm bundler](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-liferay-npm-bundler) you should get a feeling of what the bundler is doing with your files and dependencies
- In DXP:
    - The [FlatNPMBundlerProcessor processes JS Bundles](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/flat/FlatNPMBundleProcessor.java#L65-L83) to keep track of the existing packages and modules of deployed bundles.
    - The [JSResolveModulesServlet resolves the requested modules' URLs](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/servlet/JSResolveModulesServlet.java#L69-L74)
    - The [AMD Loader uses this information](https://github.com/liferay/liferay-amd-loader/blob/master/src/loader/loader.js#L258-L260) to generate the necessary dependency graph for a request and load the necessary modules on demand.

Hope this gives you the high-level overview you're looking for. 

Please, don't hesitate to ask any other doubts or concerns you might have. I assure you we're more than happy to answer and listen to whatever feedback you have. At the same time, please bear with us a little if we ever take longer to answer than expected.

Thanks!

**Comment by mfreeman-xtivia** [comment]
Thanks for the response. You're right, there have been a lot of frustrations going on lately so it was easy to get snarky--sorry.

Wrt to the FlatNPMBunderProcessor, which i had kind of stumbled my way into anyway, what triggers that to run? The presense of package.json in the bundle? or some other header in the manifest?

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, no worries. I'm sincerely sorry to hear about your struggles... I really hope we can work together to alleviate some of that pain, or at least avoid causing more :)

Currently, the [NPMRegistryImpl](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/NPMRegistryImpl.java#L65-L73) is the one that takes care of this.

It has a private [tracker](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/NPMRegistryImpl.java#L469-L489) that [tracks every single bundle addtion](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/NPMRegistryImpl.java#L239-L243) and [triggers the bundle processing](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/NPMRegistryImpl.java#L303-L307). If I remember correctly, our only processor right now is the `FlatNPMBundleProcessor` which indeed [looks for the existence of a package.json file in the artifact](https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-js/frontend-js-loader-modules-extender/src/main/java/com/liferay/frontend/js/loader/modules/extender/internal/npm/flat/FlatNPMBundleProcessor.java#L66-L70) to determine if it should continue processing the bundle.

Is this what you were looking for?

**Comment by mfreeman-xtivia** [comment]
Yes i think it is. I was trying to understand the flow of what kicked in to process the flat bundle once the JAR arrives.

I've used the config.json approach before to get modules loaded but could not find the "end of the string" here in terms of the trigger/flow for processing once a "flat" bundle arrives. 

So i assume from i have deduced from code that an npm registry "model" is created when processing the bundle, a model that can be consumed from Java. Is this npm registry model also mapped into an AMD module model at the same time, or is that not done until the servlet calls to /o/js/resolvemodule comes in the door?

**Comment by jbalsas** [comment]
> So i assume from i have deduced from code that an npm registry "model" is created when processing the bundle, a model that can be consumed from Java.

Correct

> Is this npm registry model also mapped into an AMD module model at the same time, or is that not done until the servlet calls to /o/js/resolvemodule comes in the door?

The registry only maps packages and modules regardless of module type. Modules are prepared at build time using the `[liferay-npm-bundler](https://github.com/liferay/liferay-js-toolkit/tree/master/packages/liferay-npm-bundler) which should prepare everything for final consumption.

**Comment by mfreeman-xtivia** [comment]
@jbalsas a question occurs to me now though with regard to the newest loader strategy for npm modules/loader. Given that everything is now namespaced and unique to a portlet,  doesn't this mean that if for example I have 4 React portlets on a page that i will essentially load the React framework/core 4 times as  well on that page?

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, yes, that would be the starting point which also makes it more likely that all your developments work out of the box. This makes the common case (I want to create a single React widget) straightforward.

We've blogged about this issue and the approach to solve it. Please, take a look at the [Why we need a new liferay-npm-bundler](https://liferay.dev/blogs/-/blogs/why-we-need-a-new-liferay-npm-bundler-1-of-3-) series for more context about this. By using a provider and configuring the bundler properly, you can make sure that all your developments share the same version of a given module/package.

**Comment by izaera** [comment]
@mfreeman-xtivia Have a look at this too -> https://github.com/izaera/liferay-js-toolkit-showcase/

 It's a more up-to-date showcase using imports.
