### ISSUE TITLE
Is yarn now required?

### ISSUE THREAD

**Issue by reinrl** [liferay/liferay-js-toolkit#382]
I was updated a slightly older project to 2.12.0 of the toolkit. To attempt to start from scratch, I made a new project using create-react-app, and followed the [instructions ](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-adapt-most-popular-frameworks-projects#JavaScript-create-react-app-projects) for adapting to Liferay. The application runs just fine both before and after the adapt step - but I noticed a curious bit when attempting to build for Liferay. 

Is it intentional to force yarn usage within the lnbs build portion? In the past, I believe that I had always been free to use npm or yarn interchangeably within any of the Liferay JS Toolkit pieces (and we are an NPM shop, so that is what we continued to use). Now, adapt writes yarn into the deploy:liferay script in package.json (which would be easy enough to update to use npm instead) - but the internals appear to use yarn:

```
> lnbs-build
ℹ️ Making a backup of 'src/index.js' to 'src/.index.js' before 
injecting Liferay JS Toolkit's modifications for the build.

'yarn' is not recognized as an internal or external command,
operable program or batch file.
Error: Yarn script 'build' finished with status 1
    at runYarnScript (C:\[...my path...]\node_modules\liferay-npm-build-support\lib\util.js:139:9)
```

**Comment by reinrl** [comment]
(as a side note, this was not obvious when the initial documentation on the wiki shows npm as the tool of choice for following the instructions in the "How to adapt an existing project" steps...)

**Comment by izaera** [comment]
The side note is true: I forgot to change it when we moved to `yarn` :grimacing: . I have updated the wiki :+1: .

Regarding the question, is not us who decide to use `npm` or `yarn`, it's the framework you are using who is opinionated in one way or the other. If you see the logs when running `create-react-app`, you will notice that it prefers `yarn` and in fact writes a `yarn.lock` file too. 

If we then decided to use `npm`, as we did in the first place when developing the feature, you would end up with a `yarn.lock` and a `package-lock.json` file which is not desired.

**Comment by reinrl** [comment]
Creat-react-app might be a bit opinionated...but it allows the use of either (only preferring to use yarn if it is found on your machine - but even then, you can override with --use-npm). This was just news to me, as weren't using yarn here, and now will need to (and consider the ramifications for that).

**Comment by izaera** [comment]
:-o very interesting. I didn't know that. 

Because `create-react-app` is so opinionated, I never thought they would surrender to a configurable option :-D.

We will modify it, then. I'm creating a new issue for that :point_right: #384 

Thx :-)
