### ISSUE TITLE
EEXIST error in Windows when creating build.lr\liferay folder

### ISSUE THREAD

**Issue by reinrl** [liferay/liferay-js-toolkit#383]
I initially had issues converting an existing project, so I started from scratch:

1. create-react-app my-liferay-demo
2. yo liferay-js:adapt
3. npm run build:liferay

Below is the console output/error that I received. What other information is needed to help diagnose/troubleshoot this? I see content in /build and /build.liferay - but my assumption was that I should not see the error below? I also tried adding configuration to .npmbundlerrc to generate a jar at the end of the build, and it appears that it never gets that far (I believe confirming for me that something along the way is indeed erroring, as opposed to just some general notes at the end of an otherwise successful process).

```
> my-liferay-demo@0.1.0 build:liferay C:\dev\prototyping\my-liferay-demo
> lnbs-build

ℹ️ Making a backup of 'src/index.js' to 'src/.index.js' before
injecting Liferay JS Toolkit's modifications for the build.

yarn run v1.17.3
(node:4308) ExperimentalWarning: The fs.promises API is experimental
$ react-scripts build
(node:15244) ExperimentalWarning: The fs.promises API is experimental
Creating an optimized production build...
Compiled successfully.

File sizes after gzip:

  38.54 KB  build\static\js\2.7d980bde.chunk.js
  783 B     build\static\js\runtime~main.c7442541.js
  643 B     build\static\js\main.3b3d2171.chunk.js
  517 B     build\static\css\main.2cce8147.chunk.css

The project was built assuming it is hosted at the server root.
You can control this with the homepage field in your package.json.
For example, add this to build it for GitHub Pages:

  "homepage" : "http://myname.github.io/myapp",

The build folder is ready to be deployed.
You may serve it with a static server:

  npm install -g serve
  serve -s build

Find out more about deployment here:

  https://bit.ly/CRA-deploy

Done in 37.60s.
ℹ️ Restoring backup of 'src/index.js' after React's build has finished.

{ Error: EEXIST: file already exists, mkdir 'build.liferay\jar'
    at Object.fs.mkdirSync (fs.js:854:3)
    at Renderer.render (C:\dev\prototyping\my-liferay-demo\node_modules\liferay-npm-build-support\lib\util.js:85:17)
    at generateIndexJs (C:\dev\prototyping\my-liferay-demo\node_modules\liferay-npm-build-support\lib\scripts\build\create-react-app.js:257:11)
  errno: -4075,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: 'build.liferay\\jar' }
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! my-liferay-demo@0.1.0 build:liferay: `lnbs-build`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the my-liferay-demo@0.1.0 build:liferay script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\e404rlr\AppData\Roaming\npm-cache\_logs\2019-08-19T20_22_00_122Z-debug.log
```

**Comment by reinrl** [comment]
my package.json (after create-react-app and liferay adapt:

```
{
  "name": "my-liferay-demo",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "react": "^16.9.0",
    "react-dom": "^16.9.0",
    "react-scripts": "3.1.1"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build:liferay": "lnbs-build",
    "deploy:liferay": "yarn run build:liferay && lnbs-deploy"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "liferay-npm-build-support": "^2.12.0",
    "liferay-npm-bundler": "^2.12.0",
    "liferay-npm-bundler-preset-create-react-app": "^2.12.0"
  },
  "portlet": {
    "com.liferay.portlet.display-category": "category.sample",
    "com.liferay.portlet.instanceable": true,
    "javax.portlet.name": "myliferaydemo",
    "javax.portlet.security-role-ref": "power-user,user",
    "javax.portlet.resource-bundle": "content.Language"
  }
}
```

**Comment by izaera** [comment]
Looks like a bug. The strange thing is that it never happened in my machine :thinking: 

Maybe it only happens in Windows...

**Comment by izaera** [comment]
OK, looks like mkdirSync behaves different in Windows and Linux :man_facepalming: 

I've run this in my machine:

```
$ node
> fs.mkdirSync('/tmp/test', {recursive: true})
undefined
> fs.mkdirSync('/tmp/test', {recursive: true})
undefined
> fs.mkdirSync('/tmp/test', {recursive: true})
undefined
```

So, mkdirSync doesn't complain when you try to create a directory that exists if `{recursive: true}` is passed.

However, if you run it without `recursive` you get:

```
> fs.mkdirSync('/tmp/test')
Thrown:
{ Error: EEXIST: file already exists, mkdir '/tmp/test'
    at Object.mkdirSync (fs.js:757:3)
  errno: -17,
  syscall: 'mkdir',
  code: 'EEXIST',
  path: '/tmp/test' }
```

And, apparently, in Windows, it doesn't matter whether you pass `{recursive: true}` or not. It always fail.

@reinrl  Can you confirm that for me, please? It would be a great favour... Thx :-)

**Comment by reinrl** [comment]
Correct - the first issue of the command returns undefined, and the second and all subsequent calls returns the "file already exists" error.

Is it as simple as a switch to something like this?

try {
    _fs2.default.mkdirSync(_path2.default.dirname(outputPath), { recursive: true });
  } catch (err) {
    if (err.code !== 'EEXIST') throw err
  }

(a little bit of googling had shown that, or a switch to [mkdirp](https://github.com/substack/node-mkdirp), as the recommended ways to handle a "create this directory if it doesn't exist" situation)

**Comment by izaera** [comment]
Even better that mkdirp is [fs-extra](https://www.npmjs.com/package/fs-extra) which we already use in some places (`liferay-npm-bundler` included).

It's as easy as doing `import fs from 'fs-extra';` in place of `import fs from 'fs';` and you can then call `fs.mkdirpSync()` which I guess should not throw :pray: .

**Comment by izaera** [comment]
If that does not work, I will place the try/catch to avoid adding a new dep.

**Comment by reinrl** [comment]
@izaera I have updated the pull request to use fs-extra, and the method call to be ensureDirSync(). Per the fs-extra documentation, this is the method to use - and my testing locally on windows seemed to match what I had seen in various scenarios using the previous try/catch block.

One interesting note: the scenario where a file named jar - with no extension - exists inside of /build.liferay makes the call to create the directory structure seem to think that /build.liferay/jar exists, and then the attempts to write and reference the files inside of it fails...so this method seems to have the same caveat as the try/catch block swallowing the EEXISTS condition. As I had stated in my reply to @wincent 's code review comment on my initial pull request, it feels to me like an acceptable compromise (specific to this case anyway) to recognize that a file named jar inside of a directory named build.liferay would return what is essentially a false positive. If a user manually created a file named jar (no extension) within /build.liferay, the build process would still error later on (as attempting to write files to a location that is actually itself a file would not work as intended). It is worth noting that the errors generated in such a scenario would not be entirely clear about what had happened, showing messages things like:

```
(node:15424) UnhandledPromiseRejectionWarning: Error: EEXIST: file already exists, mkdir 'C:\dev\prototyping\corpcomm_javascript_fsnviewcertificates\build.liferay\jar'
(node:15424) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:15424) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[ { Error: ENOENT: no such file or directory, stat 'C:\dev\prototyping\corpcomm_javascript_fsnviewcertificates\build.liferay\jar\react-app\asset-manifest.json'
    errno: -4058,
    code: 'ENOENT',
    syscall: 'stat',
    path: 'C:\\dev\\prototyping\\corpcomm_javascript_fsnviewcertificates\\build.liferay\\jar\\react-app\\asset-manifest.json' }
...
```
