### ISSUE TITLE
Support npm in create-react-app integration

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#384]
According to #382 , there's an option for `create-react-app` to use `npm`. Also, if `yarn` is not found, that option is automatically activated.

So we need to support that.

**Comment by izaera** [comment]
@reinrl Sadly not :-(. We are very busy bringing loaders support to the toolkit (#303) which turned out much more complex than it seemed and it's also locking any merge because of the potential conflicts that may arise.

So, if you want to give it a shot, feel free :-).

In case it is useful, my thoughts about how to resolve this issue were:

1) Look for yarn.lock or package-lock.json in the project dir as a way to detect if yarn or npm is being used. This is because when running the adapt target there doesn't seem to be any other way to know if a project is based on yarn or npm, as create-react-app doesn't leave any trace about that.
2) If both files are found or none is found, check the system for the existence of yarn and, if it exists, assume yarn, otherwise assume npm.

Optionally we may add a CLI argument in case all that fails, but I wouldn't do it until if proves necessary given that even if the autodetect fails (and that would be because you don't have yarn in your system, but want to create yarn projects without yarn.lock nevertheless :thinking: ), you can always modify the package.json manually.

**Comment by reinrl** [comment]
My initial thought was to actually use the create-react-app functionality as a model:

1. Look for yarn installed (see the function below), and set a flag for later logical flows (useYarn).
2. Whenever either yarn or npm needs to be used for something, branch based on that constant.
3. Optionally, include a command line argument to override the use of yarn (even when it exists - something like **const useYarn = useNpm ? false : shouldUseYarn();**).

```js
function shouldUseYarn() {
  try {
    execSync('yarnpkg --version', { stdio: 'ignore' });
    return true;
  } catch (e) {
    return false;
  }
}
```

Any concerns with that approach?

**Comment by reinrl** [comment]
https://github.com/liferay/liferay-js-toolkit/pull/396

**Comment by izaera** [comment]
@reinrl sorry I missed your comment from 2 days ago :-(.

Your approach looks good, but the problem I see with not checking the existence of package-lock.json and yarn.lock is that people may have yarn and npm installed in their systems and may want some projects to be npm and others to be yarn, so checking just for the existence of one or other is not as good as looking directly into the project.

AFAIK modern npm versions create package-lock.json by default and, in addition, yarn complains when it finds a package-lock.json and suggests you to remove it. So I guess checking those files is safer... :thinking: 

The case for create-react-app is different from ours, because create-react-app is creating a project from scratch so there's nothing that prevents one or the other from being used. But our adapt target acts on an already existing project, so we should honor what the project is using, I believe.

**Comment by izaera** [comment]
I have finally changed the approach. What it does now is:

1. If a package-lock.json file (alone, with no yarn.lock besides) is found in the project, use npm
2. If a yarn.lock file (alone, with no package-lock.json besides) is found in the project, use yarn
3. If both yarn.lock and package-lock.json are found or none of them:
     a. If only npm is installed in the system use npm
     b. If only yarn in installed in the system use yarn
     c. If both are installed, ask the user which one to use
