### ISSUE TITLE
The scope of `require` calls is not taken into account

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#389]
Some packages are bundled with webpack in a format that has calls to the internal webpack bundle's `require` function. For example, `pako@1.0.10` comes with a `dist/pako_deflate.js` file that has `require` calls like:

```javascript
},{}],2:[function(require,module,exports){
// String encode/decode helpers
'use strict';


var utils = require('./common');
```

That call is clearly an internal reference to the webpack bundle that is translated into submodule `1` inside the webpack bundle:

```javascript
},{"./common":1}],3:[function(require,module,exports){
```

However, the bundler thinks that it is a legitimate `require` call and puts `./common` in the list of AMD dependencies of the module thus leading to an unresolved dependency error when the AMD loaders kicks in.

There are ways in babel to know if a `require` call is globally scoped and we should probably use that to ignore non-global `require` calls.

**Comment by wsyski** [comment]
I think that my issue "Liferay npm bundler error for ngx-bootstrap 5.2.0 library #422" is caused by this error.

**Comment by wsyski** [comment]
I have just tested the patch https://github.com/liferay/liferay-js-toolkit/pull/428/commits/849475c7b6236543e92868a5c30ce7f994712fed on Liferay npm bundler error for ngx-bootstrap 5.2.0 library #422
and it did not work. Exactly the same error. I would be happy to assist you again with testing if it is of any help to you.
