### ISSUE TITLE
Cannot deploy portlet out of the box

### ISSUE THREAD

**Issue by reinrl** [liferay/liferay-js-toolkit#407]
Having worked through a few other issues/questions, I was attempting to take an out of the box example and put it through the paces:

1. Use create-react-app to create an application template (**npx create-react-app my-project** on a Windows 10 machine).
2. Use the latest Liferay-JS-Toolkit (2.13.0) to adapt the project (**npm install -g generator-liferay-js** and then **yo liferay-js:adapt**).
3. Run the project (to verify that running in standalone mode using **npm run start** functions as expected).
4. Build the project (to verify that **npm run build** and **npm run build:liferay** function as expected).
5. Deploy the project to a local Liferay instance (version 7.2).
6. Everything has gone as expected so far, so attempt to add the widget to an existing page.

I see just a blank box rendered on the page, and with "explain resolutions" turned on for the JavaScript Loader, I see the following in the console: "The following problems where detected while resolving modules: Missing required module 'my-project@1.0.0'".

I am a bit lost, as this seems like the most basic use case that I could come up (after porting some of my other portlets over to the latest pattern and having similar results, I decided to try just starting with the initial template to troubleshoot the issue). Am I missing a step somewhere? Is there something additional that I can do/try to help better narrow down the cause of the issue?

Note: I can take a previously working manually-created project, step up to 2.13.0 of both liferay-npm-build-support and liferay-npm-bundler (rerunning npm install), and have it fail to be able to be deployed to a Liferay instance. Reverting to 2.10, 2.11, or 2.12.0 all function as expected. Based on these data points, it seems reasonable to assume that it is something in the 2.13.0 release - but so far, a quick comparison of the two hasn't turned up anything obvious for me as the culprit yet...although I do see one seemingly major difference in the index.js generated by each build - the working version starts with this line (while the failing version, built using 2.13.0, does not):

```
Liferay.Loader.define("my-project@1.0.0/index", ['module', 'exports', 'require'], function(module, exports, require) {
```

(additionally, the last line of a given block appears to no longer be terminated by a semicolon throughout the generated code in the jar, if that helps point to anything)

**Comment by izaera** [comment]
@reinrl Took a bit more than expected, but finally fixed :sweat_smile: .

**Comment by reinrl** [comment]
I appreciate your efforts very much! After some initial testing, everything looks good to go on this end. Thanks again!
