### ISSUE TITLE
Offer the possibility to use Portal's React when creating a new project

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#411]
The next version of Liferay Portal will bundle a copy of React inside, so maybe we can offer developers to use it via imports instead of bundling their own. Much as we do now with Metal.

**Comment by ericdariel** [comment]
It will be great if Liferay Portal bundle a copy of React... but do you know if we can choose with an other framework like Vue or Angular ?
In our company, all our fronts are in Angular 2+, we would be disappointed if we could not use Angular.
Idem for our clients because we have many Angular Portlets and Angular Websites we can not use in the next version of Liferay Portal. (for the moment Angular Portlets are a little slow)

**Comment by izaera** [comment]
@ericdariel You can use whichever framework you want, as always have been the case :-)

The only thing I'm proposing here is to be able to reuse the built-in copy of React that goes with the portal, given that it is there and we are using it for the core product. 

It's something opportunistic, not that we want to provide copies of React, Angular and so on in the Portal for you to use them.

Using the Portal's copy of React does not come with drawbacks, either, because it couples your developments with the Portal's version which may not be what you want.

**Comment by ericdariel** [comment]
Yes, I was just thinking that if Liferay contains React why not propose to ship Angular or Vue for only those who would like to use it?

**Comment by izaera** [comment]
@ericdariel As I said you can deploy a copy of Angular in a shared bundle and reuse it among your projects. You can see an example with React in [this showcase project](https://github.com/izaera/liferay-js-toolkit-showcase/tree/react). All you need to do is the same that react-provider does but with Angular.

We don't want to ship anything outside React because:

1) There are several versions of each framework. Which one do we choose?
2) If we are not going to use them, what's the point in shipping them with the base product?
3) As a side effect, the Portal would grow bigger and slower for everybody no matter if they use Angular or not.

**Comment by izaera** [comment]
I'm closing this because it can be achieved by manual configuration (if the developers wishes) so there's no point in complicating the generator even more.

Also, if developers agree to use portal's react copy when running the generator, without knowing exactly what they are doing, they may couple their developments with portal's release lifecycle and that could ultimately lead to future unexpected problems.
