### ISSUE TITLE
JavaScript heap out of memory when i launch liferay-npm-bundler

### ISSUE THREAD

**Issue by spino233** [liferay/liferay-js-toolkit#412]
Hi,

I'm trying to transform my react project into a OSGI Modules deployable on Liferay Portal DXP 7.1.
When i launch the build script with "npm", first babel transpile the js code with success but when liferay-npm-bundler command starts after a few log like this -->  "Babel failed processing 'dependency-name' it will be copied verbatim" the build goes in out of memory. 

This is the latest log before it goes in out-of-memory :

`Babel failed processing @elastic/elasticsearch@7.2.0/-number-4/my-project/build/node_modules/@elastic%2Felasticsearch@7.2.0/api/api/xpack.usage.js: it will be copied verbatim (see report file for more info)
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/angel/projects/test-number-4/my-project/build/node_modules/@elastic%2Feui@12.4.0/dist/eui.min.js" as it exceeds the max of "500KB".
[BABEL] Note: The code generator has deoptimised the styling of "C:/Users/angel/projects/test-number-4/my-project/build/node_modules/@elastic%2Feui@12.4.0/dist/eui.js" as it exceeds the max of "500KB".

<--- Last few GCs --->

[6424:00000169F8C9BB60]   143124 ms: Mark-sweep 1316.7 (1429.8) -> 1312.7 (1427.8) MB, 2530.9 / 0.0 ms  (average mu = 0.116, current mu = 0.018) allocation failure scavenge might not succeed
[6424:00000169F8C9BB60]   145661 ms: Mark-sweep 1318.5 (1429.8) -> 1314.7 (1427.8) MB, 2475.4 / 0.0 ms  (average mu = 0.073, current mu = 0.025) allocation failure GC in old space requested

<--- JS stacktrace --->

==== JS stack trace =========================================

    0: ExitFrame [pc: 000000CDF3D5C5C1]
Security context: 0x00650911e6e9 <JSObject>
    1: push [0000006509105859](this=0x03b37e341439 <JSArray[869461]>,0x0184298dc459 <Object map = 0000039912D0E331>)
    2: append [0000037E87D30D21] [C:\Users\angel\projects\test-number-4\my-project\node_modules\babel-generator\lib\buffer.js:~64] [pc=000000CDF4B6604A](this=0x03b37e340819 <Buffer map = 00000390150F8D39>,str=
0x0072aa76b801 <String[1]: }>)
 ...

FATAL ERROR: Ineffective mark-compacts near heap limit Allocation failed - JavaScript heap out of memory
 1: 00007FF6D9BDF04A v8::internal::GCIdleTimeHandler::GCIdleTimeHandler+5114
 2: 00007FF6D9BBA0C6 node::MakeCallback+4518
 3: 00007FF6D9BBAA30 node_module_register+2032
 4: 00007FF6D9E420EE v8::internal::FatalProcessOutOfMemory+846
 5: 00007FF6D9E4201F v8::internal::FatalProcessOutOfMemory+639
 6: 00007FF6DA362BC4 v8::internal::Heap::MaxHeapGrowingFactor+9556
 7: 00007FF6DA359C46 v8::internal::ScavengeJob::operator=+24310
 8: 00007FF6DA35829C v8::internal::ScavengeJob::operator=+17740
 9: 00007FF6DA360F87 v8::internal::Heap::MaxHeapGrowingFactor+2327
10: 00007FF6DA361006 v8::internal::Heap::MaxHeapGrowingFactor+2454
11: 00007FF6D9F1CBE8 v8::internal::Factory::AllocateRawArray+56
12: 00007FF6D9F1D562 v8::internal::Factory::NewFixedArrayWithFiller+66
13: 00007FF6D9F911FC v8::internal::HashTable<v8::internal::NumberDictionary,v8::internal::NumberDictionaryShape>::KeyAt+40700
14: 00007FF6D9F90E7D v8::internal::HashTable<v8::internal::NumberDictionary,v8::internal::NumberDictionaryShape>::KeyAt+39805
15: 00007FF6D9F85546 v8::internal::HashTable<v8::internal::NumberDictionary,v8::internal::NumberDictionaryShape>::EntryToIndex+73414
16: 00007FF6DA14EE38 v8::internal::SharedFunctionInfo::SetScript+23528
17: 00007FF6DA131DE3 v8::internal::JSReceiver::class_name+20595
18: 00007FF6D9F0CFE9 v8::internal::wasm::WasmCodeManager::LookupCode+17993
19: 00007FF6D9F100A4 v8::internal::wasm::WasmCodeManager::LookupCode+30468
20: 000000CDF3D5C5C1
npm ERR! code ELIFECYCLE
npm ERR! errno 134
npm ERR! my-project@1.0.0 build: ``babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler``
npm ERR! Exit status 134
npm ERR!
npm ERR! Failed at the my-project@1.0.0 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above. `

This is my package.json : 
`{
	"name": "my-project",
	"version": "1.0.0",
	"description": "My Project",
	"devDependencies": {
		"liferay-npm-bundler": "2.7.1",
		"liferay-npm-build-support": "^2.13.1",
		"copy-webpack-plugin": "4.6.0",
		"webpack": "4.29.6",
		"webpack-cli": "3.3.0",
		"webpack-dev-server": "3.2.1",
		"babel-cli": "6.26.0",
		"babel-preset-env": "1.7.0",
		"babel-preset-react": "6.24.1",
		"babel-plugin-transform-class-properties": "^6.24.1",
		"babel-plugin-transform-es2015-destructuring": "^6.23.0",
		"babel-plugin-transform-object-rest-spread": "^6.26.0",
		"babel-loader": "7.1.5"
	},
	"dependencies": {
		"react": "16.8.6",
		"react-dom": "16.8.6",
		"@elastic/datemath": "^5.0.2",
		"@elastic/elasticsearch": "7.2.0",
		"@elastic/eslint-plugin-eui": "0.0.1",
		"@elastic/eui": "^12.3.1",
		"moment": "^2.24.0",
		"query-string": "^6.8.1",
		"react-router-dom": "^5.0.1",
		"react-scripts": "3.0.1"
	},
	"scripts": {
		"build": "babel --source-maps -d build src && npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"deploy": "npm run build && lnbs-deploy",
		"start": "lnbs-start"
	},
	"portlet": {
		"com.liferay.portlet.display-category": "category.sample",
		"com.liferay.portlet.header-portlet-css": "/css/styles.css",
		"com.liferay.portlet.instanceable": true,
		"javax.portlet.name": "myproject",
		"javax.portlet.security-role-ref": "power-user,user",
		"javax.portlet.display-name": "My Project"
	},
	"main": "src/index.js"
}
`This is my npmbundlerrc : 
``{
    "exclude": "node_modules",
	"create-jar": {
		"output-dir": "dist",
		"features": {
			"js-extender": true,
			"web-context": "/my-project",
			"configuration": "features/configuration.json"
		}
	},
	"dump-report": true
}
`

Where is the problem?

Thanks for watching this.

**Comment by izaera** [comment]
This doesn't look like a problem with the tool. It's just that you node.js ran out of memory. Try increasing the heap limit and see if that helps.

Nobody else has reported anything similar, so I'm inclined to think that this is not a bug in the tool itself, but just a configuration setting in your machine. However, if it keeps failing, feel free to reopen this issue and provide the information needed to reproduce it. For example, attach a ZIP of your project or a simpler one where the issue is also reproducible.

Thanks.
