### ISSUE TITLE
Impossible to deploy an Angular portlet if option "Use Loader Version 4.x" is active

### ISSUE THREAD

**Issue by ericdariel** [liferay/liferay-js-toolkit#417]
With liferay 7.1 fixpack 11, if we activate "Use Loader Version 4.x" option, and we try to deploy a new Angular portlet made with the yeoman liferay-js, the portlet doesn't works.
We must desactivate the option "Use Loader Version 4.x", add the portlet and it works. 
After that we can reactivate the option.

**Comment by izaera** [comment]
@ericdariel You should use our JIRA for portal related errors :point_right: https://issues.liferay.com. 

There are myriads of things involved between the JS Toolkit and the final execution of the portlet and we (the development team) don't control all of them (starting with released portal versions and fixpacks, for example).

I'm closing this. Feel free to ask any doubt you may have about the error reporting process in this issue and I'll try to help you.
