### ISSUE TITLE
Liferay npm bundler error for ngx-bootstrap 5.2.0 library

### ISSUE THREAD

**Issue by wsyski** [liferay/liferay-js-toolkit#422]
I am following the pattern of 
https://github.com/liferay/liferay-blade-samples/tree/7.1/maven/apps/npm-deduplication-portlets

Trying to use ngx-bootstrap/modal in angular-provider.

Unfortunately in my angular consumer portlet get the following error:

liferay-amd-loader | 
 A require() call has failed but no failure handler was provided.
 Note that even if the call stack of this error trace looks like coming from the Liferay AMD Loader, it is not an error in the Loader what has caused it, but an error caused by the require() call.
 The reason why the Loader is in the stack trace is because it is printing the error so that it doesn't get lost.
 However, we recommend providing a failure handler in all require() calls to be able to recover from errors better and to avoid the appearance of this message.
 
 Some information about the require() call follows:
   · Require call id: 3 
   · Required modules: Array(1) 
   · Missing modules: (n/a) 
   · Stack trace of the require() call: 
        Error
            at e.value (http://localhost:6080/o/frontend-js-web/loader/loader.js:1:5898)
            at default_1 (http://localhost:6080/o/js/resolved-module/calendar@4.0.0/lib/index.js?languageId=en_US:9:24)
            at http://localhost:6080/web/guest/events:4591:17
            at http://localhost:6080/o/frontend-js-web/loader/loader.js:1:7907
            at http://localhost:6080/o/frontend-js-web/loader/loader.js:1:7689 
 Error: The following problems where detected while resolving modules:
    · Missing dependency 'common-portlet-provider$ngx-bootstrap@5.2.0/bundles/ngx-bootstrap-modal.umd' of 'calendar@4.0.0/lib/calendar/components/event-detail.component'
    · Missing dependency 'common-portlet-provider$ngx-bootstrap@5.2.0/bundles/ngx-bootstrap-modal.umd' of 'calendar@4.0.0/lib/calendar/components/register-attendee.component'
    · Missing dependency 'common-portlet-provider$ngx-bootstrap@5.2.0/bundles/ngx-bootstrap-modal.umd' of 'calendar@4.0.0/lib/calendar/calendar-event-list.module'
    at e.value (loader.js:1)
    at loader.js:1
    at ZoneDelegate.invoke (zone.js:358)
    at Zone.run (zone.js:143)
    at zone.js:842
    at ZoneDelegate.invokeTask (zone.js:383)
    at Zone.runTask (zone.js:186)

Should not be:
'common-portlet-provider$ngx-bootstrap@5.2.0/modal/bundles/ngx-bootstrap-modal.umd' instead of
'common-portlet-provider$ngx-bootstrap@5.2.0/bundles/ngx-bootstrap-modal.umd' 

'common-portlet-provider$ngx-bootstrap@5.2.0/modal/bundles/ngx-bootstrap-modal.umd'  exists, while 'common-portlet-provider$ngx-bootstrap@5.2.0/bundles/ngx-bootstrap-modal.umd' does not exist.
Do you have any hints what should I do? What I am missing? Thanks in advance

**Comment by wsyski** [comment]
Actually the same problem could be recreated much simpler. Here are the steps:
1. Generate angular portlet with yo
2. add 		"ngx-bootstrap": "5.2.0" to dependencies
3. app.component.ts
import {ModalModule} from 'ngx-bootstrap/modal';
imports: [
		BrowserModule,
		ModalModule.forRoot(),
	],

The following error occurs in liferay-amd-loader 4.2
Some information about the require() call follows:
   · Require call id: 1 
   · Required modules: ["liferay-portlet@1.0.0"] 
   · Missing modules: (n/a) 
   · Stack trace of the require() call: 
        Error
            at e.value (http://localhost:6080/o/frontend-js-web/loader/loader.js:1:5898)
            at http://localhost:6080/web/guest/test2:4550:17 
 Error: The following problems where detected while resolving modules:
    · Missing dependency 'liferay-portlet$ngx-bootstrap@5.2.0/bundles/ngx-bootstrap-modal.umd' of 'liferay-portlet@1.0.0/app/app.module'
    at e.value (loader.js:440)
    at loader.js:284

**Comment by wsyski** [comment]
It is very likely that this issue is a duplicate to: The scope of `require` calls is not taken into account #389

**Comment by wsyski** [comment]
[liferay-portlet.zip](https://github.com/liferay/liferay-js-toolkit/files/3675186/liferay-portlet.zip)
I have just tested the patch https://github.com/liferay/liferay-js-toolkit/pull/428/commits/849475c7b6236543e92868a5c30ce7f994712fed
and it did not work. Please find the complete example attached to the case. I would be happy to assist you again with testing if it is of any help to you.

**Comment by izaera** [comment]
https://issues.liferay.com/browse/IFI-1072

**Comment by izaera** [comment]
As shown in the report file, the `name-amd-modules` is giving the missing module an incorrect name:

![imagen](https://user-images.githubusercontent.com/3273630/66197605-0897db80-e69b-11e9-8e7d-ef1ec32c6c8b.png)

Note that the module file is `liferay-portlet$ngx-bootstrap@5.2.0/modal/bundles/ngx-bootstrap-modal.umd.js` but the module name is being composed like `liferay-portlet$ngx-bootstrap/modal@5.2.0/bundles/ngx-bootstrap-modal.umd` (it is missing the `/modal` before the `/bundles`).

**Comment by izaera** [comment]
I have made a test with node and it doesn't use the `name` field of internal `package.json` files, so for example, if you make a project like these:

index.js
>console.log(require("renamed"));

folder/package.json
>{
>  "name": "renamed"
>}

folder/index.js
>module.exports = "perico";

and run `node index.js` in the root package folder, it fails.

That's good news because it means that we can ignore these `package.json` files' name field.

So, fixing this apparently equates to fixing the method `getPackageDir()` from `liferay-npm-build-tools-common/lib/packages`.

**Comment by izaera** [comment]
The `package.json` in the intermediate folder has a `version` field, which is the main criterion we were using to differentiate root `package.json`s from intermediate ones.

So, I will add another check to fix it.

**Comment by izaera** [comment]
It's not just that. It needs to be fixed in the server too :disappointed:

**Comment by izaera** [comment]
So, I finally fixed this :sweat_smile: 

Unfortunately it needs a server side fix too (which is sent to master CE but needs to be backported to released versions), so it's not enough to patch the bundler.

**Comment by wsyski** [comment]
I have tested the latest branch of liferay portal 7.2.x (bf315cb38943ced0bccfbec27f1422a1528e1ed2) with liferay-js-toolkit ver.  2.13.3 and my example attached earlier to the case still does not work
