### ISSUE TITLE
Very first, basic 'import' from React/Material-UI library causes `Unexpected token 'export'` error

### ISSUE THREAD

**Issue by Muzietto** [liferay/liferay-js-toolkit#438]
I am using Liferay 7.1.3-ga4. I have a sample portlet where I test React apps. Now I am trying to use MaterialUI.

The sample package.json I am using is [here](https://github.com/Muzietto/vagrantfiles-dockerfiles/blob/material-ui-stuff/liferay/legacy/7.1.3-ga4/react-portlet/package.json).

As soon as I try to import the simplest component (not even using it in my code), as I do [here](https://github.com/Muzietto/vagrantfiles-dockerfiles/blob/material-ui-stuff/liferay/legacy/7.1.3-ga4/react-portlet/src/App.js#L8) causes the following error message at console:

![image](https://user-images.githubusercontent.com/2652413/66503168-02549580-eac7-11e9-9ed6-91e0769094aa.png)

If I drill down the error on the console, I can see that it is generated by code which is supposed to decorate some "global Jss instance". I am fairly new to Liferay, so this is obscure to me.

![image](https://user-images.githubusercontent.com/2652413/66503354-59f30100-eac7-11e9-8899-d3e7732b5f45.png)

By checking out [this issue](https://github.com/liferay/liferay-js-toolkit/issues/365) I kinda understand that there are hickups with the ES6 syntax and that there is a [config file](https://github.com/izaera/liferay-js-toolkit-showcase/blob/material-ui/.npmbundlerrc) that could show me how to do things.

I will check it thoroughly tomorrow. But I'd appreciate a lot any hint and assistance meanwhile.

**Comment by Muzietto** [comment]
One more thing: I have followed your guidelines for reporting a problem. In particular, I have cleaned up the build directory before each attempt.

**Comment by Muzietto** [comment]
I managed to sort things out by using your https://github.com/izaera/liferay-js-toolkit-showcase

It was a matter of correct versions for babel and material-ui plus that long and convoluted .npmbundlerrs.

@izaera - Thank you very much!!

**Comment by izaera** [comment]
@Muzietto I think the problem you are experiencing is #365 . It will be fixed in the next release and you will be able to clean your `.npmbundlerrc` ;-)
