### ISSUE TITLE
Problem building react component

### ISSUE THREAD

**Issue by ViktorHSN** [liferay/liferay-js-toolkit#450]
Hello,

I am trying to export a react component into my company's Liferay portal. I am using the yo generator with liferay-js-toolkit. My component runs ok in webpack with npm start, but when I try to build I get the following error:

![image](https://user-images.githubusercontent.com/7051143/68393358-a2dfb900-014a-11ea-9e50-a261bfb48e5e.png)

my ruleset for this build is:

![image](https://user-images.githubusercontent.com/7051143/68393415-c4d93b80-014a-11ea-8698-6052a8376f3c.png)

If it helps, here is the npm log error:

![image](https://user-images.githubusercontent.com/7051143/68393503-f18d5300-014a-11ea-8274-3dd46d2d627f.png)

**Comment by alberamon** [comment]
I have the same problem, if you have "react-scripts": "3.2.0" dependency try to delete it and compile. This works for me.

**Comment by izaera** [comment]
@ViktorHSN this is most probably fixed in the latest bundler version. 

Can you check it and if it keeps failing reopen the issue?

Thx :-).
