### ISSUE TITLE
Error when loading a external css file from node_modules

### ISSUE THREAD

**Issue by oliveiraaraujo** [liferay/liferay-js-toolkit#459]
**Description**
We tried to load "leaflet.css" from "node_modules/leaflet/dist/leaflet.css" without success nevertheless we load successfully "leaflet.js" with "import L from 'leaflet';" according all instructions at  https://loop.liferay.com/es/home/-/loop/feed/19699790 

**Background:**
    Liferay 7.2 Master
    I'm tried to load "leaflet.css"  from  node_modules/leaflet/dist/leaflet.css using "import styles from 'leaflet/dist/leaftlet.css';" on a js component.

my configuration files:

.npmbundlerrc
``` json
{
	"rules": [
		{
			"test": "\\.css$",
			"use": ["css-loader"]
		}
	]
}
```
package.json
``` json
{
	"dependencies": {
		"leaflet": "^1.6.0",
		"liferay-npm-bundler-loader-css-loader": "^2.14.1"
	}
}
```

**browser error mesage:**
```
Unable to load /o/app-builder-web/../../../node_modules/leaflet/dist/leaflet.css
```

**Comment by MarcoPortillo** [comment]
@oliveiraaraujo I had the same issue, only workaround I found was copy the .css file from the node_modules into the assets folder of the project, and import it as a normal css file in the style.css.

CSS files loaded from node_modules won't work.

**Comment by oliveiraaraujo** [comment]
Hi @MarcoPortillo , it worked to me after I replace "liferay-npm-bundler-loader-css-loader" to "liferay-npm-bundler-loader-style-loader".
But I dont know if it will work as well when the css file have relative dependencies like images and fonts.

**Comment by Sastidar** [comment]
I'm facing the same issue...
