### ISSUE TITLE
Shared Bundle with the npm using '@' and '/' - e.g. '@fullcalendar/core'

### ISSUE THREAD

**Issue by arthuroy** [liferay/liferay-js-toolkit#483]
Hi,

I followed the document, [Package De-duplication](https://portal.liferay.dev/docs/7-2/reference/-/knowledge_base/r/how-the-liferay-npm-bundler-publishes-npm-packages#package-de-duplication), to make a shared bundle, `testdrive-fullcalendar-support`.

The npm packages used in this bundle are `@fullcalendar/core` ... (listed below)

`package.json`
```json
{
	"name": "testdrive-fullcalendar-support",
	"version": "1.0.0",
	"description": "Fullcalendar",
	"devDependencies": {
		"liferay-npm-bundler": "^2.16.2",
		"liferay-npm-build-support": "^2.16.2"
	},
	"dependencies": {
		"@fullcalendar/core": "4.3.1",
		"@fullcalendar/daygrid": "4.3.0",
		"@fullcalendar/vue": "4.3.1"
	},
	"scripts": {
		"build": "npm run copy-assets && liferay-npm-bundler",
		"copy-assets": "lnbs-copy-assets",
		"deploy": "npm run build && lnbs-deploy"
	}
}
```

After `npm run deploy`, I access the following URL:

http://localhost:8080/o/js/resolved-module/@testdrive-fullcalendar-support$fullcalendar%2Fcore@4.3.1/main.css

The browser show:
```
HTTP Status 400 – Bad Request
Message Invalid URI: noSlash
Description The server cannot or will not process the request due to something that is perceived to be a client error (e.g., malformed request syntax, invalid request message framing, or deceptive request routing).
```

I also tried to escape the percent sign, but still failed (the page is redircted to `http://localhost:8080/web/guest/home`):

http://localhost:8080/o/js/resolved-module/@testdrive-fullcalendar-support$fullcalendar%252Fcore@4.3.1/main.css

`manifest.json`

```json
{
  "packages": {
    "@fullcalendar/core@4.3.1": {
      "dest": {
        "dir": "./build/node_modules/@testdrive-fullcalendar-support$fullcalendar%2Fcore@4.3.1",
        "id": "@testdrive-fullcalendar-support$fullcalendar/core@4.3.1",
        "name": "@testdrive-fullcalendar-support$fullcalendar/core",
        "version": "4.3.1"
      },
      "modules": {
        "main.js": {
          "flags": {
            "esModule": true
          }
        }
      },
      "src": {
        "dir": "./node_modules/@fullcalendar/core",
        "id": "@fullcalendar/core@4.3.1",
        "name": "@fullcalendar/core",
        "version": "4.3.1"
      }
    }
}
```

Platform:
- Microsoft Windows 10 1909 (18363.535)
- Liferay CE 7.2.1 GA2
- liferay-npm-bundler 2.16.2

**Comment by izaera** [comment]
You are requesting a CSS file, not a JS module. Are you using the corresponding loader to process CSS files? 

Read the [bundler's manual](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-liferay-npm-bundler) and the [list of loaders](https://github.com/liferay/liferay-js-toolkit/wiki/List-of-loaders) on how to configure them.

You probably want to use `css-loader` or `style-loader`.

**Comment by izaera** [comment]
I'm closing this as answered. Feel free to reopen it if you have further problems.

**Comment by arthuroy** [comment]
@izaera

The CSS file is just for example, the `.js` file cannot be accessed.

http://localhost:8080/o/js/resolved-module/@testdrive-fullcalendar-support$fullcalendar%2Fcore@4.3.1/main.js

`@testdrive-fullcalendar-support$fullcalendar%2Fcore@4.3.1/main.js` cannot be accessed, because the `@` (the one before `testdrive-fullcalendar-support`) and `%2F` characters.

### Problems

- The share bundle name is `testdrive-fullcalendar-support`.
- The node_module to access is `@fullcalendar/core`.

Problem 1:

The `@` symbol of the node_module, `@fullcalendar/core`, is prefixed to the shared bundle name, `@testdrive-fullcalendar-support`.

Problem 2:

The `/` symbol of the node_module, `@fullcalendar/core`, will be translated to `%2F` for the build output as the part of the directory name, `build\node_modules\@testdrive-fullcalendar-support$fullcalendar%2Fcore@4.3.1\`.

But, `%2F` causes the problem, HTTP Status 400 – Bad Request (Invalid URI: noSlash).

Failed even escaping the percent sign `%` to `%25`.

**Comment by arthuroy** [comment]
Ahhh... it works

http://localhost:8080/o/js/resolved-module/@testdrive-fullcalendar-support$fullcalendar/core@4.3.1/main.css

I should not use `%2F` (which comes from the build output `build/modules` and `META-INF\resources\node_modules\` in the .jar file)

http://localhost:8080/o/js/resolved-module/@testdrive-fullcalendar-support$fullcalendar%2Fcore@4.3.1/main.css

Thanks for your time and patience.
