### ISSUE TITLE
Getting FrameworkEvent ERROR on deploying the react module to Liferay Portal

### ISSUE THREAD

**Issue by techieravishah** [liferay/liferay-js-toolkit#486]
Hi, 

We are using Liferay portal CE 7.1.3 GA4 CE. We have created a react template using https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-generator-liferay-js. And we have simply added a dependency https://www.npmjs.com/package/@react-pdf/renderer in package.json and have done npm install. 

Note: We are not making any changes to the code, only we are adding the react-pdf/renderer dependency. and when we run the module using npm run start it works fine. We can see the output of the sample code.  When we do the npm run deploy which creates a jar and copies it to the Liferay portal, In that case, it is throwing Framework Event Error. Please check the logs below: 

> 2020-01-06 08:23:21.021 INFO  [fileinstall-D:/projects/demo/runtime/liferay-ce-portal-7.1.3-ga4/osgi/modules][BundleStartStopLogger:42] STOPPED pdf-renderer_1.0.0 [1014]
2020-01-06 08:23:22.306 INFO  [Refresh Thread: Equinox Container: 10277629-c239-4b05-99dd-3fa95ce7a705][BundleStartStopLogger:39] STARTED pdf-renderer_1.0.0 [1014]
2020-01-06 08:23:26.437 ERROR [Framework Event Dispatcher: Equinox Container: 10277629-c239-4b05-99dd-3fa95ce7a705][com_liferay_frontend_js_loader_modules_extender:97] FrameworkEvent ERROR

We also checked the output by checking the URL: http://localhost:8081/o/js_resolve_modules?modules=pdf-renderer%401.0.0 and it is giving us the following output: 

> {
pathMap: { },
configMap: { },
resolvedModules: [
":ERROR:Missing required module 'pdf-renderer@1.0.0'"
],
explanation: [
":ERROR:Missing required module 'pdf-renderer@1.0.0'"
],
moduleMap: { },
}

I am not sure about what could be the issue. Deploying it to the Liferay portal creates this error and the same works in the standalone js toolkit mode. Please let us know if more details are needed. 

Thanks,
Ravi Shah

**Comment by izaera** [comment]
This is a bug in the portal. I'm creating a [LPS](https://issues.liferay.com/browse/LPS-106622) to fix it.

**Comment by techieravishah** [comment]
Thanks Ivan. I will watch the LPS for the same.

**Comment by techieravishah** [comment]
Hi Ivan, 

How can I get this fix? https://issues.liferay.com/browse/LPS-106622

**Comment by izaera** [comment]
If you have a support contract you will need to check with our support department. Otherwise, I think you need to wait for it to be included in a new community edition release.

**Comment by techieravishah** [comment]
Thanks @izaera for providing the solution in such a short time. Really appreciate it. I will try to build the module-ext from your commit and will check if that solves my problem as of now. I will update you if any issues.

**Comment by techieravishah** [comment]
Hi Ivan, 

I was trying to build the module ext but I was not able to find any such class 

> Manifest manifest = new Manifest(packagesJSONObject);

Could you help in finding out where I can get Manifest?

**Comment by izaera** [comment]
TBH I don't know how to build modules outside of [Liferay's source tree](https://github.com/liferay/liferay-portal). I always work with the portal's master version. Sorry.
