### ISSUE TITLE
Custom Fragment Editor?

### ISSUE THREAD

**Issue by mfreeman-xtivia** [liferay/liferay-js-toolkit#490]
I know this might be a bit outside the strict scope of this repo, but does anyone know if its possible to build a custom editor for fragments on the server side?

What i am imagining or hoping for is that perhaps I could implement a unique editor as a portlet or OSGi module to supplant/augment the existing 4-pane editor. Is this even remotely possible now or is the existing editor pretty much baked in as-is?

Thanks
--Mike

**Comment by jbalsas** [comment]
Hey @mfreeman-xtivia, the Fragment Editor is owned by the Echo team, which is, as you guessed, a complete different team than that maintaining the `js-toolkit` :)

I think the existing editor is pretty much what it is. Its main entry points are, afaict:
- [edit_fragment_entry.jsp](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/edit_fragment_entry.jsp)
- [FragmentEditor.es.js](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/js/FragmentEditor.es.js)
- [FragmentEditor.soy](https://github.com/liferay/liferay-portal/blob/master/modules/apps/fragment/fragment-web/src/main/resources/META-INF/resources/js/FragmentEditor.soy)

By overriding the `.soy` and `.js` files, you should be able to modify the whole behaviour, but that's for sure easier said than done.

I'd suggest filing a feature request in [issues.liferay.com](https://issues.liferay.com/secure/Dashboard.jspa) detailing your needs so the team can consider how to bring it to reality if possible.

Hope that helps!
