### ISSUE TITLE
Problem with import css from node modules

### ISSUE THREAD

**Issue by ddellai** [liferay/liferay-js-toolkit#492]
I was able to create an angular 8 portlet and everything works fine. Then, I tried to import angular material library and use some components. It's working, but I had to import the `material-theme.css` inside my `style.scss` in the `assets/css folder `of the project. Is there any way to import the css file directly from the node modules? I tried in this way 

`@import '~@angular/material/theming';`

but it's not working because it seems that liferay can't find the path. 
I would avoid to put the entire css of the theme inside my custom style, is that possibile?
If it helps, I imported my style from the `package.json` in this way:` "com.liferay.portlet.header-portlet-css": "/css/styles.css"`. @izaera have You got a workaround for that?
 
Thanks in advance

**Comment by izaera** [comment]
What do you mean with "liferay can't find the path"? Why would "liferay" resolve an import inside a .scss file? It's the responsibility of the Sass compiler to resolve such imports, isn't it? :thinking:

**Comment by izaera** [comment]
I'm closing this as it doesn't look like a bundler issue and haven't got any reply.
