### ISSUE TITLE
Adapted React App: Logo broken because of hash prefix filenames

### ISSUE THREAD

**Issue by chrberndt** [liferay/liferay-js-toolkit#512]
Steps to reproduce: 

```
npx create-react-app my-app
cd my-app
yo liferay-js:adapt
```
Use suggested values / answers in adapt wizard

Start vanilla instance of Liferay 7.3.0 CE GA1

```
yarn run build:liferay
yarn run deploy:liferay
```

Install "my-app" on a portal page

Result: logo is broken and the server warns: 

```
2020-02-24 08:33:44.413 WARN  [http-nio-8080-exec-7][code_jsp:?] {code="404", msg="ProxyServlet: /o/my-app-0.1.0/static/media/logo.5d5d9eef.svg", uri=/o/my-app-0.1.0/static/media/logo.5d5d9eef.svg}
```

Expected result: the logo path is properly resolved. 

Environment: 

Liferay 7.3.0 CE GA1

```
java -version

openjdk version "1.8.0_242"
OpenJDK Runtime Environment (build 1.8.0_242-8u242-b08-1~deb9u1-b08)
OpenJDK 64-Bit Server VM (build 25.242-b08, mixed mode)

node -v
v10.15.1


yo@3.1.1

generator-liferay-js@2.18.2

```

package.json of my-app: 

```
{
  "name": "my-app",
  "version": "0.1.0",
  "private": true,
  "dependencies": {
    "@testing-library/jest-dom": "^4.2.4",
    "@testing-library/react": "^9.3.2",
    "@testing-library/user-event": "^7.1.2",
    "react": "^16.12.0",
    "react-dom": "^16.12.0",
    "react-scripts": "3.4.0"
  },
  "scripts": {
    "start": "react-scripts start",
    "build": "react-scripts build",
    "test": "react-scripts test",
    "eject": "react-scripts eject",
    "build:liferay": "lnbs-build",
    "deploy:liferay": "yarn run build:liferay && lnbs-deploy"
  },
  "eslintConfig": {
    "extends": "react-app"
  },
  "browserslist": {
    "production": [
      ">0.2%",
      "not dead",
      "not op_mini all"
    ],
    "development": [
      "last 1 chrome version",
      "last 1 firefox version",
      "last 1 safari version"
    ]
  },
  "devDependencies": {
    "liferay-npm-build-support": "^2.18.2",
    "liferay-npm-bundler": "^2.18.2",
    "liferay-npm-bundler-preset-create-react-app": "^2.18.2"
  },
  "portlet": {
    "com.liferay.portlet.display-category": "category.sample",
    "javax.portlet.name": "myapp",
    "javax.portlet.security-role-ref": "power-user,user",
    "javax.portlet.resource-bundle": "content.Language",
    "com.liferay.portlet.instanceable": true
  }
}
```

**Comment by lgdd** [comment]
I have the same issue when trying to use SVG, it tries to fetch the file without webpack hash in the name (`/static/media/icons.svg`), while loading JPG works fine and is loaded with the hash (e.g. `/static/media/background.78c7cf25.jpg`).

**Comment by izaera** [comment]
> it tries to fetch the file without webpack hash in the name ...

@lgdd you mean it tries to always fetch files with the hash (from the client side) but some of the files (.eot, .svg, .otf, .ttf, .woff, and .woff2) get their hashes removed during the build and thus fail (because the request is -say- `/static/media/icons.4cd67d.svg` but the file is stored as `/static/media/icons.svg` in the JAR. Don't you?

**Comment by lgdd** [comment]
@izaera I have to say that my comment wasn't very clear. The current behaviour is exactly what you described:

![liferay-js-toolkit--issue-512](https://user-images.githubusercontent.com/3501902/83625982-16d52900-a595-11ea-9e23-a1a1a37a265d.jpg)

**Comment by izaera** [comment]
@lgdd Great :+1: I wanted to make sure in case I was missing anything. Thx.
