### ISSUE TITLE
Migrate vue-cli adaptation to bundler 3

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#523]

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.

**Comment by wincent** [comment]
Autumn cleaning is the best!

![leaf-blower](https://user-images.githubusercontent.com/7074/95847323-db214b80-0d4c-11eb-91e1-0e23d39f6347.gif)
