### ISSUE TITLE
Create a tool to lint imports/exports

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#528]
We will definitely need some tool to be able to check if a certain project using imports will be able to satisfy all its dependencies given the definition of its provider. 

Per [this comment](https://github.com/liferay/liferay-js-toolkit/issues/520#issuecomment-592408732) we should be able to inspect during build time if a project will be able to run or will fail with some missing dependency during runtime (we wouldn't be able to cover the case where the runtime provider is compatible with the one used in the build, but not exactly the same, but if that caused an error it would be the user's fault, nonetheless, for breaking the semver semantics).

In the event of some missing modules we would warn the user and tell him the modifications needed in the provider to fix the problem.

**Comment by izaera** [comment]
In bundler 2 we didn't have this problem because everything was exported always. But now that the user has to configure exports explicitly, developers will be in a situation where they need to declare the exports for a package they didn't write (f.e: `react` or `lodash`). 

The only way I can think of to make this easy is to inspect the consumers for every import/require call they make and find the list of entry points that should be exported in the provider. 

Other than that, it looks like a quite complex task to decide which entry points to export a priori, depending on the structure of the framework and how familiar the developer is with that specific framework.

**Comment by izaera** [comment]
Warn when importing the same modules we are exporting (f.e: if someone mistakenly configures the default portal preset in an infrastructure module providing packages).

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
