### ISSUE TITLE
Backport new bundler 2 bugs to bundler 3

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#530]
The following bugs have been merged to branch `develop` while `3.x-WIP` was active, so we need to backport them:

* #514
* #498
* #545  
* #513 
* #553
* #567

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
