### ISSUE TITLE
Add release script

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#534]
Like #518 but for real releases (needs more checks and steps to be taken).

**Comment by izaera** [comment]
I have configured liferay-js-publish (#579 and #580) but because we are not yet using the `master` branch it fails. I won't fix it yet and will try to keep going with manual pre-releases until we decide to release the first production release.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
