### ISSUE TITLE
Fail when configuration object does not match the API schema

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#536]
Like webpack does, fail if the object returned from `liferay-npm-bundler.config.js` does not match the expected schema.

This is intended to ease migration from bundler 2 and to avoid difficult to spots errors due to typos.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
