### ISSUE TITLE
Generate report file

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#538]
We want the same report file we had but with different information:

1. How imports were processed (where and what)
2. What goes inside webpack bundles
3. Performance times ?

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
