### ISSUE TITLE
Exported external modules should have .js appended if needed

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#539]
If I export, for instance:

```
	"exports": {
		"recharts": "recharts",
		"recharts_lib_index": "recharts/lib/index"
	}
```

A file named `recharts/lib/index` (without the `.js`) is created to export that entry point. 

It should have the `.js` appended automatically.

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
