### ISSUE TITLE
Generate correct manifest

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#540]
Bundler 3 is not generating flags and information for modules in `manifest.json` any more. We should do it (or at least know if it is OK that it is missing) to maintain backwards compatibility.

**Comment by jbalsas** [comment]
I'd start by `know if it is OK that it is missing`... it's always been hard for my to figure out wether this is needed or not...

**Comment by izaera** [comment]
I think we will be lucky, because it was mostly needed for the ES6 module flags hack (the loader needed to know in advance if a module was transpiled from ES6). But now that we are bundling everything with webpack, I think that's not needed any more.

However, I'm still investigating.

**Comment by izaera** [comment]
Right now we are using the `manifest.json` for two things:

1. **Add module flags** (as per #368): needed for circular dependencies, but can be used as a general mechanism to pass metadata regarding modules from the JS Toolkit directly to the NPM Registry.
2. **Map namespaced module names**: for example `react` to `frontend-js-web-react$react`. 

I think 2 was needed for the bridges functionality, which mapped unversioned package names to a specific version to maintain backwards compatibility with the pre-bundler architecture.

As far as I can tell, we don't need 1 because we can't have circular dependencies in the current setup. I'm unsure if we could end up having circular deps via imports, but I think we can delay that and, if it happens, we just need to add the necessary flags to the `manifest.json` file.

Regarding 2, it is normally not needed, but any module using bridges will need the manifest to be present so I would say we should generate it as in bundler 2, at least until we get rid of bridges...

Any thoughts? @jbalsas @wincent

**Comment by izaera** [comment]
Just to give an example of 2: `frontend-js-web` declares bridges in the `.npmbridgerc` file to map all the `frontend-js-web/liferay/*` modules to an unversioned name, so that people can do:

```javascript
Liferay.Loader.require('frontend-js-web/liferay/events')
```

without any need to specify the current `frontend-js-web` version like in:

```javascript
Liferay.Loader.require('frontend-js-web@4.0.10/liferay/events')
```

**Comment by wincent** [comment]
> Regarding 2, it is normally not needed, but any module using bridges will need the manifest to be present so I would say we should generate it as in bundler 2, at least until we get rid of bridges...

IIUC, that sounds reasonable.
