### ISSUE TITLE
Provide information how to use liferay-js:adapt with portlet extender

### ISSUE THREAD

**Issue by jtumano** [liferay/liferay-js-toolkit#556]
Please provide information how to wrap adopted application with js extender main function. 

In my case Vue application steps I tried: 

- `vue create some-app` (created typescript project config)
- `cd some-app`
- `yo liferay-js:adapt`
- edit **src/main.ts** - wrap **new Vue({...})** with **export default main({config, portletElementId, portletNamespace, contextPath})**

Expected result: after deploy portlet will be shown
Actual: nothing is shown and no information in console

Check source code if needed here: https://github.com/jtumano/liferay-js-adapt-extended-issue

**Comment by izaera** [comment]
:thinking: I don't think that's possible. You may [adapt a native framework project](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-adapt-most-popular-frameworks-projects) or use [the pure JS portlet approach](https://github.com/liferay/liferay-js-toolkit/wiki/How-to-use-generator-liferay-js) but not combine both.

It's one or the other.

**Comment by izaera** [comment]
I'm closing this as answered. Feel free to reopen again if further questions arise.
