### ISSUE TITLE
liferay-npm-bundler-preset-angular-cli Example(s)

### ISSUE THREAD

**Issue by elycruz** [liferay/liferay-js-toolkit#558]
Hi, 
  It would super helpful if you guys can have a "usage" section (in the readme or elsewhere) with some quick examples on how to get this working with latest angular cli project (angular 9 project et al.).

Quick context note: In my project I keep getting module time out when adding my module as a widget to a page (I'm using Liferay 7.1 and 7.2.).  

Thank you,
Cheers

**Comment by elycruz** [comment]
Ignore issue.  I know understand how this works.  Thank you. 👍 .

**Comment by izaera** [comment]
Regarding the timeout, you can increase it inside the Portal in Control Panel > Configuration > System Settings > Frontend Infrastructure > Loader
