### ISSUE TITLE
Review source maps

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#565]
Before releasing we must check the generated source maps and their virtual locations so that, when seen in the dev tools, they make sense.

Also, we need to make sure that the source maps are useful and don't have incorrect or too generic mappings.

**Comment by izaera** [comment]
After investigating this I have arrived to a point where source maps are almost working but only for the cases where a sourcemap does not carry multiple origin files (as is the case with webpack bundles, where several input `.js` files are merged inside one single `bundle.js` file).

However, because we need to wrap webpack bundles inside an AMD define call while not breaking the source maps, we need to implement a source map manipulator to be able to do that transformation.

AFAIK, nobody has done that yet. There are a few packages in npm to merge source maps, but they don't support multiple origins (possibly because the algorithm is quite complex and I'm not even sure if generalizable).

**Comment by izaera** [comment]
Nevertheless I will send a PR with the WIP since it is a small enhancement to what we had and I don't want to lose it (even if it won't be part of the final solution).

**Comment by jbalsas** [comment]
Doing some autumn cleaning as we move this project to https://github.com/liferay/liferay-frontend-projects#js-toolkit

We'll be curating these and creating new ones mostly from scratch to have a better sense of where we want to go.
