### ISSUE TITLE
How to read custom session attribute in react portlet LR7.2

### ISSUE THREAD

**Issue by deepakpoilil** [liferay/liferay-js-toolkit#573]
i have set session value in postlogin hook like this. 
HttpSession ses = lifecycleEvent.getRequest().getSession( ses.setAttribute("LIFERAY_SHARED_PING_URL","somevalue");

how can i read this session value in my react portlet deployed in Liferay 7.2

**Comment by izaera** [comment]
Sorry, but this project is only related to the JS Toolkit, not the use of the Liferay Platform as a whole. 

Consider using the Community Slack or the Forums to make questions related to the Liferay Platform, they have more exposure and will be more helpful, for sure :-).

Thanks and sorry for the inconvenience.
