### ISSUE TITLE
Build failed when components use shorthand for React.Fragment

### ISSUE THREAD

**Issue by andrewatliferay** [liferay/liferay-js-toolkit#599]
I can confirm that using <React.Fragment/> does allow me to leverage the fragment in the markup, but when I try to use the shorthand notation <></> in my return markup I get an error:

SyntaxError: src/components/Comments.js: Unexpected token (36:13)
  34 |     else
  35 |         return(
> 36 |             <>
     |              ^
  37 |                 <h3><i className="fal fa-comments-alt pr-3"></i> Comments</h3>
  38 |                 {
  39 |                     (data.items.length == 0) ? <small>Start a conversation - be the first to comment!</small> : ''

**Comment by izaera** [comment]
You should configure your `.babelrc` file correctly. The JS Toolkit is not responsible to transpiling your source code: it is done as a build step prior to executing `liferay-npm-bundler`.

**Comment by andrewatliferay** [comment]
Hi Ivan, 

Thanks for the details -- something else to figure out hahah (I'm newish to all this). One more comment though. According to documentation I found, the React framework added this shorthand notation in 16.2. The liferay-js tools generated for me a skeleton project with 16.8 as the version so I would argue that developers might expect to be able to use it (just based on versions). 

Can the necessary babelrc changes be added as part of the generated skeleton project?

**Comment by izaera** [comment]
Hi again. After thinking more about it, I'm unsure if the shorthand notation is a matter of tweaking the `.babelrc` file, as everything you are supposed to put there is the react preset and it is there by default :thinking: 

As you say, [fragments are available since 16.2](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html) so I have to investigate this a bit more...

**Comment by izaera** [comment]
Found it. [This is the reason](https://reactjs.org/blog/2017/11/28/react-v16.2.0-fragment-support.html#babel).

You need Babel 7 for the shorthand `</>` notation to work and we still use Babel 6. So, the only workaround for now is to use `<React.Fragment>`
