### ISSUE TITLE
Angular adapted portlet MS Edge cache issue

### ISSUE THREAD

**Issue by SabyasachiChattaraj** [liferay/liferay-js-toolkit#609]
Changes made to Angular adapted portlet in Edge (edgeHTML) does not show up. It needs manual cache clear. But the same thing works fine in chrome

Steps :
1. Create and deploy Angular adapted portlet
2. Shows up fine in both Chrome and MS Edge
3. Introduce a button in app.component.html
4. Redeploy
5. Button shows up upon page reload in Chrome but not in Edge
6. If you clear cache in Edge and reload then button shows up.

**Comment by izaera** [comment]
This has to do with the server caches, not the JS Toolkit. In general it's a good practice to disable server caches when developing, as Liferay Portal sometimes practices a very aggressive caching strategy.

You can see recommended developer settings in the [portal-developer.properties](https://github.com/liferay/liferay-portal/blob/7.3.2-ga3/portal-impl/src/portal-developer.properties) file of the Portal's source tree.
