### ISSUE TITLE
blank after "Bundle-SymbolicName" in META-INF/MANIFEST.MF cause jar failed to be deployed

### ISSUE THREAD

**Issue by Wujae** [liferay/liferay-js-toolkit#613]
The blank after property "Bundle-SymbolicName", "Bundle-Version", "Bundle-Name", "Web-ContextPath" in META-INF/MANIFEST.MF generated by command "liferay-npm-bundler“, seems to cause OSGiException while deploying the jar.

I traced the source code and found out that :
**get content()** method in **liferay-npm-bundler/src/jar/manifest.ts** return serveral blanks after those property mentioned above.

**Comment by Wujae** [comment]
I forgot to add "description" proprety in package.json which cause a blank value in "Bundle-Name"

**Comment by izaera** [comment]
I will reopen it then, so that we can use the `name` when no `description` is found. :+1:
