### ISSUE TITLE
Add specific build for fragments

### ISSUE THREAD

**Issue by izaera** [liferay/liferay-js-toolkit#625]
With big probability we may need to tailor a specific build for fragments as part of [LPS-102280](https://issues.liferay.com/browse/LPS-102280). We could also do it in the fragments toolkit with webpack, but I believe it will be much better to do it in the JS Toolkit to reuse the functionality we already have in place to transform files and projects.

**Comment by jbalsas** [comment]
Closing since I think this is done now, or should be moved to https://github.com/liferay/liferay-frontend-projects#js-toolkit
