### ISSUE TITLE
Yarn Build in a mandatory command

### ISSUE THREAD

**Issue by manoelcyreno** [liferay/liferay-js-toolkit#640]
# Step-by-Step:
1. clone the repo
1. go to the root folder and type "yarn"

# Actual result:
the error will appears

# Expected:
the command works without error

# Environment:
it happened in the master and in the 3.x-WIP branches
I'm using a macOS Catalina v10.15.6
node v10.15.1
yarn v1.22.4

# log:
```
yarn install v1.22.4
[1/4] 🔍  Resolving packages...
[2/4] 🚚  Fetching packages...
[3/4] 🔗  Linking dependencies...
[4/4] 🔨  Building fresh packages...
[-/5] ⠈ waiting...
[2/5] ⠈ fsevents
[-/5] ⠈ waiting...
[-/5] ⠈ waiting...
warning Error running install script for optional dependency: "/Users/manoelcyreno/Projects/ENG/FrontendInfra/liferay-js-toolkit/node_modules/fsevents: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments:
Directory: /Users/manoelcyreno/Projects/ENG/FrontendInfra/liferay-js-toolkit/node_modules/fsevents
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.8.0
gyp info using node@10.15.1 | darwin | x64
gyp info spawn /usr/local/bin/python2
gyp info spawn args [ '/usr/local/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/manoelcyreno/Projects/ENG/FrontendInfra/liferay-js-toolkit/node_modules/fsevents/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/local/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/Users/manoelcyreno/.node-gyp/10.15.1/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/Users/manoelcyreno/.node-gyp/10.15.1',
gyp info spawn args   '-Dnode_gyp_dir=/usr/local/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/Users/manoelcyreno/.node-gyp/10.15.1/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/Users/manoelcyreno/Projects/ENG/FrontendInfra/liferay-js-toolkit/node_modules/fsevents',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
No receipt for 'com.apple.pkg.CLTools_Executables' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLILeo' found at '/'.

No receipt for 'com.apple.pkg.DeveloperToolsCLI' found at '/'.

gyp: No Xcode or CLT version detected!
gyp ERR! configure error
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at ChildProcess.emit (events.js:189:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:248:12)
gyp ERR! System Darwin 19.6.0
gyp ERR! command \"/usr/local/bin/node\" \"/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js\" \"rebuild\"
gyp ERR! cwd /Users/manoelcyreno/Projects/ENG/FrontendInfra/liferay-js-toolkit/node_modules/fsevents
✨  Done in 12.38s.
```

**Comment by izaera** [comment]
I've tried to reproduce it but, in Linux, that doesn't happen, which is logical given that what is failing is a compilation of native code.

Looking at the `No receipt for ... found ...` error, it looks like you have a problem with licensing in your setup. Try [this](https://github.com/schnerd/d3-scale-cluster/issues/7#issuecomment-564595771) and see if it helps...

**Comment by wincent** [comment]
I think the thing about the failed compilation might a red herring because it is an optional dependency, which means Yarn ignores the error.

The actual problem that @manoelcyreno told me he was going to report is that `yarn test` didn't work on a fresh clone of the project (I can repro that); dies with a bunch of `Cannot find module 'liferay-npm-build-tools-common/lib/file-path' from 'index.test.js'` errors.

**Comment by wincent** [comment]
Edited to add:

> Works after a `yarn build` of course, but it would be nice to detect that case and print a non-confusing message instead.

**Comment by izaera** [comment]
I'm looking now at the [README](https://github.com/liferay/liferay-js-toolkit#setup) and it specifies that you must run `yarn build` before `yarn test` so I think I will leave it like it is.

Reasons for that are:

1) It's not trivial to check if the build is up-to-date (of course I can test if a certain output file exists, but that doesn't guarantee that everything is correctly setup)
2) If I make the `test` script run `yarn build` before it will make development slower or more cumbersome. 

So, given that tests are usually ran after building (if a developer invokes them) or automatically by CI servers (if QA invokes them) I think it is OK like it is now.
