### ISSUE TITLE
Portlet localization doesn't work correctly

### ISSUE THREAD

**Issue by jtumano** [liferay/liferay-js-toolkit#641]
After creation vue portlet by generator it has example code with using Liferay.Language.get method. It kinda works in js file but doesn't work correctly if I want to extract it to separate method or use directly in vue components. 

Check a bit modified index.js example code: 
```js
export default function main({portletNamespace, contextPath, portletElementId, configuration}) {
    
    const node = document.getElementById(portletElementId);

    const translate = key => Liferay.Language.get(key);
    
    // Dynamically write markup to portlet's node
    node.innerHTML = `
        <div>
            <div>
                <span class="tag">${translate('portlet-namespace')}:</span> 
                <span class="value">{{portletNamespace}}</span>
            </div>
            <div>
                <span class="tag">${Liferay.Language.get('context-path')}:</span>
                <span class="value">{{contextPath}}</span>
            </div>
            <div>
                <span class="tag">${Liferay.Language.get('portlet-element-id')}:</span>
                <span class="value">{{portletElementId}}</span>
            </div>
            
            <div>
                <span class="tag">${Liferay.Language.get('configuration')}:</span>
                <span class="value pre">{{JSON.stringify(configuration, null, 2)}}</span>
            </div>
            
        </div>
    `;
```

Here I extracted `Liferay.Language.get` into function and trying to pass a lang key as a parameter. As a result - it renders **portlet-namespace** instead of translated value. 

Another example in component: 
```vue
<template>
  <div>
    Liferay.Language.get('context-path') <!-- renders 'Context Path' with quotes! -->
    {{ Liferay.Language.get('context-path') }} <!-- fails, because vue tries to get Liferay from 'this' object -->
    {{ translate('context-path') }} <!-- function is same as in above mentioned code block, renders context-path untranslated
  </div> 
</template>
```

Also, window.Liferay.Language.get does not return translation

If I'm getting correctly there is a very stupid implementation which just parses when loading whole portlet code with some regexp pattern and looks for smth like Liferay.Language.get('') with key and replaces it with a found translation. any trying to use it JS way fails

**Comment by izaera** [comment]
Hi @jtumano.

Sadly, `Liferay.Language.get()` is not an API that can be used to do dynamic localization (see [this document](https://github.com/liferay/liferay-frontend-guidelines/blob/master/dxp/resource_serving.md#language-filter) about how resources are served by Liferay).

As you can see, your strategy will never work because the filter only knows how to replace static keys :-(.
