### ISSUE TITLE
Use liferay data on react-portlet

### ISSUE THREAD

**Issue by JairoDuarte** [liferay/liferay-js-toolkit#650]
I want to know how can I display a list of articles in Liferay blog with react portlet (pure JavaScript project)? how can I have access to Liferay data from react portlet?

**Comment by izaera** [comment]
You need to fetch the data from the server using remote APIs or any other mechanism you define.

**Comment by JairoDuarte** [comment]
How can I fetch the data from the API with the current user session? it's possible if not it means I need authentic the user twice times, one for the API and the other for the application right.

**Comment by izaera** [comment]
@JairoDuarte This repo is just for the JS Toolkit part, not the whole Liferay architecture, and the question you are asking goes far beyond the JS Toolkit.

I would suggest using [Liferay's Forums](https://liferay.dev/forums) to ask that type of questions. There's more people there, and someone will be able to help you better :-).

**Comment by JairoDuarte** [comment]
ok I'll do it, Thanks @izaera.
