### ISSUE TITLE
sharing JS between react-portlets with error: Missing dependency ':ERROR:Missing version constraints

### ISSUE THREAD

**Issue by nachoge** [liferay/liferay-js-toolkit#657]
Hello,

I'm tring to share some modules used by diferents react-portles. That is a 'common' react portlet providing JS to others. This way the commons remain centralized. 

I'm using liferay 7.2

I've used the following blog: https://liferay.dev/blogs/-/blogs/sharing-js-across-modules

using the projects provided worked as espected.

It seems he uses a different mechanism to build and deploy that the one provided by the template eclipse offers (and the sames as in most examples for react-portlets): 

build": "babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources && liferay-npm-bundler" 

I have one react-portlet called 'commons-react' with some js. In his bnd there's an entry: Provide-Capability: soy; type="commons-react"; version: Version="1.0.0"

There's another react-portlet called commons-react-consumer In his bnd there's an entry: Require-Capability:soy; type="commons-react"; version:Version="1.0.0"

in consumer there's a js importing a module this way:

import ArqICA from 'commons-react/lib/ArqICA.js';

in the working example there's a similar import
import {add, multiply} from 'js-utils/util.es';

when built and deployed using:

build": "babel --source-maps -d build/resources/main/META-INF/resources src/main/resources/META-INF/resources && liferay-npm-bundler" 

the following errors appears at run time (executinf the portlet)

· Missing dependency ':ERROR:Missing version constraints for commons-react-consumer$commons-react in package.json of commons-react-consumer@1.0.0/lib/ArqICA' of 'commons-react-consumer@1.0.0/lib/index.es'

so, What I'm doing wrong? 
Do I have any misconfiguration? Should I define the module  by using:  Liferay.Loader.define(....) in the main js (defined 
 in package.json)

Thanks in advance!
Nacho

**Comment by izaera** [comment]
That blog post is a bit outdated. Better use this, which also shows how to share react between different project :point_right: https://github.com/izaera/liferay-js-toolkit-showcase/tree/react#liferay-js-toolkit-showcase

Note, however, that the example doesn't use any Java tool, just plain `npm` and JavaScript tools. I don't know if that suits your setup....

Still, it is worth having a look at it, to understand the underlying concepts.

**Comment by izaera** [comment]
If you still need help with the project setup you are describing, you should file an issue using DXP support or ask in the forums/Slack, because this project is only related to the JavaScript parts of the build, not the whole Java+JavaScript build.

**Comment by nachoge** [comment]
Hi,

finally I've been able to share modules...

as simple as definig the config in .npmbundlerrc. So right know I'm referencing modules (js resources) via

import <exported ES6 class> from '<resource-provider-module>/<theResource>' instead of
import <exported ES6 class> from './<theResource>

in any case I will check your blog in deep



Thank you very much!

**Comment by nachoge** [comment]
Way the way... Just to mention
What I mentioned about Provide/Require Capability directive in the bnd file seems to not affect the behaviour (right now the are working without those directives).

Again thanks

**Comment by izaera** [comment]
:+1:
