### ISSUE TITLE
react access liferay theme display

### ISSUE THREAD

**Issue by JairoDuarte** [liferay/liferay-js-toolkit#659]
I would know if it's possible to passe the Liferay theme display object to the bootstrap of react application as you did with portletNamespace, contextPath, and other objects?

**Comment by jwanner83** [comment]
`themeDisplay` is a global Variable which should be accessible without doing anything in your application either through `themeDisplay` directly or through `Liferay.ThemeDisplay`.

**Comment by izaera** [comment]
Thanks for replying @jwanner83 :-). I will close this, then.

**Comment by JairoDuarte** [comment]
Thank you @jwanner83  for your answer.
